In [4]:
import numpy as np

#Vectores

# Vectores

- xdddddd

In [5]:
A=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
B=np.matrix([[-1,2,-3],[2,5,1],[-2,1,6]])
print("A:",A)
print("B:",B)

A: [[1 2 3]
 [4 5 6]
 [7 8 9]]
B: [[-1  2 -3]
 [ 2  5  1]
 [-2  1  6]]


In [6]:
A.shape

(3, 3)

In [7]:
A+B

matrix([[ 0,  4,  0],
        [ 6, 10,  7],
        [ 5,  9, 15]])

In [8]:
A-B

matrix([[2, 0, 6],
        [2, 0, 5],
        [9, 7, 3]])