In [11]:
import numpy as np
import sympy as sym

### -CODIFICACION

In [34]:
#Abecedario Cifrado
A,B,C,D,E,F,G,H,I,J,K,L,M,N,Ñ,O,P,Q,R,S,T,U,V,W,X,Y,Z,_=sym.symbols("A,B,C,D,E,F,G,H,I,J,K,L,M,N,Ñ,O,P,Q,R,S,T,U,V,W,X,Y,Z,_")
_=0
A=1
B=2
C=3 
D=4 
E=5 
F=6 
G=7 
H=8 
I=9 
J=10 
K=11 
L=12
M=13 
N=14 
Ñ=15 
O=16 
P=17 
Q=18 
R=19 
S=20 
T=22 
U=22 
V=23 
W=24 
X=25 
Y=26 
Z=27

#----Gracias---
print("Palabra a codificar: Gracias")
#..Codificando--
#MatrixClave "A"
A_Clave=np.matrix([[1,1,0],[1,0,1],[0,1,0]])
print ("Matriz Clave",A_Clave)
       
#Codificando-----PAR---
COD1=A_Clave*np.matrix([[P],[A],[R]])
#COD1
COD1[0]%28
COD1[1]%28
COD1[2]%28
#--------------------#
COD2=A_Clave*np.matrix([[A],[_],[B]])
COD2[0]%28
COD2[1]%28
COD2[2]%28
#--------------------#
COD3=A_Clave*np.matrix([[O],[L],[I]])
COD3[0]%28
COD3[1]%28
COD3[2]%28
#--------------------#
COD4=A_Clave*np.matrix([[V],[I],[A]])
COD4[0]%28
COD4[1]%28
COD4[2]%28
#--------------------#
print("-->PAR: ",COD1[0]%28,COD1[1]%28,COD1[2]%28)
print("--->PAR , codificado Q H A ")
#--------------------#
print("-->A_B: ",COD2[0]%28,COD2[1]%28,COD2[2]%28)
print("--->A_B , codificado A C _")
#--------------------#
print("-->OLI: ",COD3[0]%28,COD3[1]%28,COD3[2]%28)
print("--->OLI , codificado _ X L")
#--------------------#
print("-->VIA: ",COD4[0]%28,COD4[1]%28,COD4[2]%28)
print("--->VIA , codificado D W I")
#--------------------#
#--------------------#
print("-->>>Mensaje  codificado a enviar es : QHAAC__XLDNWI")


Palabra a codificar: Gracias
Matriz Clave [[1 1 0]
 [1 0 1]
 [0 1 0]]
-->PAR:  [[18]] [[8]] [[1]]
--->PAR , codificado Q H A 
-->A_B:  [[1]] [[3]] [[0]]
--->A_B , codificado A C _
-->OLI:  [[0]] [[25]] [[12]]
--->OLI , codificado _ X L
-->VIA:  [[4]] [[24]] [[9]]
--->VIA , codificado D W I
Mensaje  codificado a enviar es : QHAAC__XLDNWI


## -DECODIFICACION

In [40]:
#DESCIFRANDO EL MENSAJE
# MATRIZ (LLAVE)
A_inv=np.linalg.inv(A_Clave)
print("Matriz de descifrado:",A_inv)
#------Codificado: QHA
DEC1=A_inv*np.matrix([[Q],[H],[A]])
#COD1
DEC1[0]%28
DEC1[1]%28
DEC1[2]%28
#------Codificado: AC_
DEC2=A_inv*np.matrix([[A],[C],[_]])
DEC2[0]%28
DEC2[1]%28
DEC2[2]%28
#------Codificado: _XL
DEC3=A_inv*np.matrix([[_],[X],[L]])
DEC3[0]%28
DEC3[1]%28
DEC3[2]%28
#------Codificado: DWI
DEC4=A_inv*np.matrix([[D],[W],[I]])
DEC4[0]%28
DEC4[1]%28
DEC4[2]%28
#--------------------#
print("->QHA: ",DEC1[0]%28,DEC1[1]%28,DEC1[2]%28)
print("--->QHA , codificado P A R")
#--------------------#
print("->AC_: ",DEC2[0]%28,DEC2[1]%28,DEC2[2]%28)
print("--->AC_ , codificado A _ B")
#--------------------#
print("->_XL: ",DEC3[0]%28,DEC3[1]%28,DEC3[2]%28)
print("--->_XL , codificado O L I")
#--------------------#
print("->DWI: ",DEC4[0]%28,DEC4[1]%28,DEC4[2]%28)
print("--->DWI , codificado V I A")
#--------------------#
#--------------------#
print("-->>>Mensaje  descifrado  es : PARA_BOLIVIA")


Matriz de descifrado: [[ 1.  0. -1.]
 [-0. -0.  1.]
 [-1.  1.  1.]]
->QHA:  [[17.]] [[1.]] [[19.]]
--->QHA , codificado P A R
->AC_:  [[1.]] [[0.]] [[2.]]
--->AC_ , codificado A _ B
->_XL:  [[16.]] [[12.]] [[9.]]
--->_XL , codificado O L I
->DWI:  [[23.]] [[9.]] [[1.]]
--->DWI , codificado V I A
-->>>Mensaje  descifrado  es : PARA_BOLIVIA
