### Ejercicio 1.-
-Crear un vector "V" de sies componentes con entradas aleatorias entre 0 y 1, luego hallar el promedio de las componentes.

In [7]:
import numpy as np
from numpy import*

In [19]:
vector=[20,10,10,50,10]
vectorA=np.array(lista)
print(vector)
print(np.sum(vector))
print(np.mean(vector))

[20, 10, 10, 50, 10]
100
20.0


-Estudiante: Juan Carlos  Mendoza Marquez 

### Ejercicio 2.-
-Crear los vectores u=[1,4,6] y v=[-6,6,-3] y hallar
--a) El modulo de ambos vectores 
---b) El producto escalar del vector u con el vector v 
---¿Es el vector u perpendicular al vector v?

In [29]:
u=[1,4,6]
u=np.array(u)
print(u)
print(u*2)
u1=(np.sum(u))
print(np.sum(u))
print(np.sqrt(u1))

[1 4 6]
[ 2  8 12]
11
3.3166247903554


In [35]:
v=[-6,6,-3]
v=np.array(v)
print(v)
print(v*2)
v1=(np.sum(v))
print(np.sum(v))
#no se puede sacar una raiz negativa 

[-6  6 -3]
[-12  12  -6]
-3


In [37]:
uv= np.array([[1,-1,1],
              [1, 4, 6],
              [-6, 6, -3]])
print(uv)
np.linalg.det(A)

[[ 1 -1  1]
 [ 1  4  6]
 [-6  6 -3]]


In [8]:
B=np.array([[ 1,  5, 5, 5, 5],
            [ 5,  2, 5, 5, 5],
            [ 5,  5, 3, 5, 5],
            [ 5,  5, 5, 4, 5],
            [ 5,  5, 5, 5, 5]])
print(B)
np.linalg.det(B) 

[[1 5 5 5 5]
 [5 2 5 5 5]
 [5 5 3 5 5]
 [5 5 5 4 5]
 [5 5 5 5 5]]


119.99999999999987